<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('menu_items')->truncate();

        $menuItems = [
            // --- De Entradas.jpeg ---
            ['name' => 'Causa Rellena de Pollo', 'description' => 'Causa acompañado de sarsa de cebolla', 'price' => 17.00, 'category' => 'Entradas'],
            ['name' => 'Chilcano Especial de Trucha', 'description' => 'Caldito con trocitos de trucha', 'price' => 10.00, 'category' => 'Entradas'],
            ['name' => 'Crema de Rocoto', 'description' => 'Papitas en crema de Rocoto Picante', 'price' => 18.00, 'category' => 'Entradas'],
            ['name' => 'Mondongo', 'description' => 'Solo Domingos y Feriados', 'price' => 15.00, 'category' => 'Entradas'],
            ['name' => 'Tequeños rellenos de queso', 'description' => '12 Tequeños rellenos de queso + guacamole', 'price' => 14.00, 'category' => 'Entradas'],
            ['name' => 'Caldo de Cordero', 'description' => 'Solo Sábados, Domingos y Feriados', 'price' => 18.00, 'category' => 'Entradas'],
            ['name' => 'Alitas a la BBQ', 'description' => 'Alitas en salsa Barbacoa acompañado con papitas fritas', 'price' => 17.00, 'category' => 'Entradas'],
            ['name' => 'Papa a la Huancaína', 'description' => 'Papitas en salsa huancaína de casa', 'price' => 16.00, 'category' => 'Entradas'],
            ['name' => 'Porción de ensalada', 'description' => null, 'price' => 6.00, 'category' => 'Entradas'],
            ['name' => 'Porción de Cancha con queso', 'description' => null, 'price' => 4.00, 'category' => 'Entradas'],
            ['name' => 'Porción de Arroz', 'description' => null, 'price' => 3.00, 'category' => 'Entradas'],

             // --- De Cuy y Pollo.jpeg ---
            ['name' => 'Cuy Chactado Entero', 'description' => 'Cuy entero frito apanado con harina de maiz, papas doradas, choclo y sarsa criolla', 'price' => 75.00, 'category' => 'Cuy'],
            ['name' => 'Picante de Cuy Entero', 'description' => 'Cuy entero frito bañado en salsa de maní con arroz blanco y papas sancochadas', 'price' => 65.00, 'category' => 'Cuy'],
            ['name' => 'Cuy Dorado Entero', 'description' => 'Cuy entero dorado, papas doradas, arroz blanco y ensalada de lechuga', 'price' => 65.00, 'category' => 'Cuy'],
            ['name' => 'Picante de Cuy 1/2', 'description' => 'Cuy ½ frito bañado en salsa de maní con arroz blanco y papas sancochadas', 'price' => 35.00, 'category' => 'Cuy'],
            ['name' => 'Cuy Dorado 1/2', 'description' => 'Cuy dorado de ½, papas doradas, arroz blanco y ensalada de lechuga', 'price' => 35.00, 'category' => 'Cuy'],
            ['name' => 'Picante de Cuy 1/4', 'description' => 'Cuy ¼ frito bañado en salsa de maní con arroz blanco y papas sancochadas', 'price' => 25.00, 'category' => 'Cuy'],
            ['name' => 'Cuy Dorado 1/4', 'description' => 'Cuy dorado de 1/4, papas doradas, arroz blanco y ensalada de lechuga', 'price' => 25.00, 'category' => 'Cuy'],
            ['name' => 'Pechuga a lo Pobre', 'description' => 'Filete de pollo, arroz, papas doradas, ensalada, huevo, hot dog y plátano frito', 'price' => 26.00, 'category' => 'Pollo'],
            ['name' => 'Milanesa de Pollo', 'description' => 'Pollo empanizado con galleta y frito, arroz, papas fritas y ensalada', 'price' => 26.00, 'category' => 'Pollo'],
            ['name' => 'Pollo a la Plancha', 'description' => 'Filete de pollo, papas doradas, arroz y ensalada', 'price' => 22.00, 'category' => 'Pollo'],
            ['name' => 'Milanesa a lo Pobre', 'description' => 'Pollo empanizado con galleta, arroz, papas fritas, ensalada, huevo, Hot Dog y Plátano Frito', 'price' => 30.00, 'category' => 'Pollo'],
            ['name' => 'Chicharrón de Pollo', 'description' => 'Trozos de pollo, papas doradas y ensalada', 'price' => 22.00, 'category' => 'Pollo'],

            // --- Resto de la carta ---
            ['name' => 'Pachamanca 4 Sabores', 'description' => 'Cuy, Carnero, Cerdo, Pollo, Papas, Habas, Camote y 3 Humitas', 'price' => 60.00, 'category' => 'Pachamancas'],
            ['name' => 'Pachamanca 3 Sabores', 'description' => 'Carnero, Cerdo, Pollo, Papas, Habas, Camote y 2 Humitas', 'price' => 48.00, 'category' => 'Pachamancas'],
            ['name' => 'Pachamanca 2 Sabores', 'description' => '2 presas a escoger, Papas, Habas, Camote y 1 Humita', 'price' => 37.00, 'category' => 'Pachamancas'],
            ['name' => 'Pachamanca 1 Sabor', 'description' => '1 presa a escoger, Papas, Habas, Camote y 1 Humita', 'price' => 28.00, 'category' => 'Pachamancas'],
            ['name' => 'Especial PaChaCuy', 'description' => 'Cuy, Caja China, Papas, Habas, Camote y 2 Humitas', 'price' => 45.00, 'category' => 'Pachamancas'],
            ['name' => 'Humitas Dulces', 'description' => null, 'price' => 2.50, 'category' => 'Pachamancas'],
            ['name' => 'Mixito', 'description' => 'Ceviche de trucha, Causita de Pollo, Plátano y camote frito', 'price' => 30.00, 'category' => 'Truchas'],
            ['name' => 'Causa Acevichada', 'description' => 'Causa de pollo y Ceviche de trucha', 'price' => 40.00, 'category' => 'Truchas'],
            ['name' => 'Mix de Trucha', 'description' => 'Ceviche de trucha y Chicharrón de trucha', 'price' => 38.00, 'category' => 'Truchas'],
            ['name' => 'Trucha Frita', 'description' => '1 trucha entera frita, papas doradas, Arroz blanco, ensalada de lechuga', 'price' => 22.00, 'category' => 'Truchas'],
            ['name' => 'Trucha a la Parrilla', 'description' => '1 trucha entera hecha en parrilla, papas doradas, Arroz blanco, ensalada de lechuga', 'price' => 22.00, 'category' => 'Truchas'],
            ['name' => 'Ceviche de Trucha', 'description' => 'Trozos de trucha con limón, camote, lechuga, cebolla y canchita', 'price' => 30.00, 'category' => 'Truchas'],
            ['name' => 'Ceviche con Chilcano', 'description' => 'Trozos de trucha con limón, camote, lechuga, cebolla y canchita + chilcano de trucha', 'price' => 35.00, 'category' => 'Truchas'],
            ['name' => 'Chicharrón de Trucha', 'description' => 'Trozos de trucha deshuesada, papas doradas y ensalada de lechuga', 'price' => 25.00, 'category' => 'Truchas'],
            ['name' => 'Milanesa de Trucha', 'description' => 'Filete de trucha deshuesada y empanizada, papas fritas + ensalada de lechuga', 'price' => 28.00, 'category' => 'Truchas'],
            ['name' => 'Ronda Huancavelicana', 'description' => 'Picante de cuy, chicharrón de chancho, chuño passi, Apanado de res, papita y sarsa criolla', 'price' => 65.00, 'category' => 'Super Especiales'],
            ['name' => 'Ronda Especial Los Pinos', 'description' => 'Causa de pollo, ceviche de trucha, chicharrón de trucha, Leche de tigre, plátano y camote frito + canchita', 'price' => 60.00, 'category' => 'Super Especiales'],
            ['name' => 'Mix Challwa', 'description' => 'Trucha a la parrilla, Ceviche de trucha, chicharrón de trucha', 'price' => 50.00, 'category' => 'Super Especiales'],
            ['name' => 'Ronda Mixta', 'description' => 'Causa de pollo, Ceviche de trucha y chicharrón de trucha', 'price' => 50.00, 'category' => 'Super Especiales'],
            ['name' => 'Triple CCC', 'description' => 'Arroz chaufa de trucha, Ceviche de trucha y causa de pollo', 'price' => 40.00, 'category' => 'Super Especiales'],
            ['name' => 'Mix Caja Picante', 'description' => 'Picante de Cuy, Chanchito a la caja china y arroz amarillo', 'price' => 40.00, 'category' => 'Super Especiales'],
            ['name' => 'Triple Wanka Willka', 'description' => 'Picante de cuy, Papa a la Huancaína, Chicharrón de chancho + porción de arroz', 'price' => 45.00, 'category' => 'Super Especiales'],
            ['name' => 'Bisteck a lo Pobre', 'description' => 'Bisteck, papas fritas, arroz, ensalada, huevo, hot dog y plátanos fritos', 'price' => 32.00, 'category' => 'Carnes'],
            ['name' => 'Bisteck Simple', 'description' => 'Bisteck, papas fritas, arroz y ensalada', 'price' => 30.00, 'category' => 'Carnes'],
            ['name' => 'Lomo Saltado (Lomo Fino)', 'description' => 'Arroz, papas fritas y lomo saltado', 'price' => 30.00, 'category' => 'Carnes'],
            ['name' => 'Lomo Montado (Lomo Fino)', 'description' => 'Arroz, papas fritas y lomo saltado más huevo a la inglesa', 'price' => 32.00, 'category' => 'Carnes'],
            ['name' => 'Lomo Saltado a lo Pobre (Lomo Fino)', 'description' => 'Arroz, papas fritas y lomo saltado más huevo a la inglesa, Plátano y Hot Dog', 'price' => 35.00, 'category' => 'Carnes'],
            ['name' => 'Chanchito a la caja china con papa y choclo', 'description' => 'Sábado y Domingo', 'price' => 30.00, 'category' => 'Carnes'],
            ['name' => 'Chanchito a la caja China con Chuño', 'description' => 'Sábado y Domingo', 'price' => 30.00, 'category' => 'Carnes'],
            ['name' => 'Chicharrón Colorado de Chancho', 'description' => 'Trozos de chicharrón con ají colorado, papas y Arroz Amarillo', 'price' => 25.00, 'category' => 'Carnes'],
            ['name' => 'Chicharrón Dorado de Chancho', 'description' => 'Trozos de chicharrón, papas doradas, sarsa criolla y canchita', 'price' => 22.00, 'category' => 'Carnes'],
            ['name' => 'Chuño con Chicharrón Colorado', 'description' => 'Trozos de chicharrón Colorado, chuño y sarsa criolla', 'price' => 25.00, 'category' => 'Carnes'],
            ['name' => 'Tallarín a la Huancaína con Pechuga', 'description' => null, 'price' => 30.00, 'category' => 'Pastas'],
            ['name' => 'Tallarín a la Huancaína con Bisteck de Res', 'description' => null, 'price' => 32.00, 'category' => 'Pastas'],
            ['name' => 'Tallarín a la Huancaína con Lomo Saltado (Lomo Fino)', 'description' => null, 'price' => 35.00, 'category' => 'Pastas'],
            ['name' => 'Tallarín Verde con Pechuga', 'description' => null, 'price' => 30.00, 'category' => 'Pastas'],
            ['name' => 'Tallarín Verde con Bisteck de Res', 'description' => null, 'price' => 32.00, 'category' => 'Pastas'],
            ['name' => 'Tallarín Verde con Caja China', 'description' => 'Sábados y Domingos', 'price' => 32.00, 'category' => 'Pastas'],
            ['name' => 'Tallarín Verde con Apanado de Res', 'description' => null, 'price' => 30.00, 'category' => 'Pastas'],
            ['name' => 'Tallarín Saltado de Lomo Fino', 'description' => null, 'price' => 28.00, 'category' => 'Pastas'],
            ['name' => 'Tallarín a la Huancaína con Milanesa de Pollo', 'description' => null, 'price' => 30.00, 'category' => 'Pastas'],
            ['name' => 'Tallarín Verde con Papa a la Huancaína', 'description' => null, 'price' => 28.00, 'category' => 'Pastas'],
            ['name' => 'Tallarín Verde con Lomo Saltado', 'description' => null, 'price' => 35.00, 'category' => 'Pastas'],
            ['name' => 'Banana Split', 'description' => null, 'price' => 14.00, 'category' => 'Postres'],
            ['name' => 'Machupicchu', 'description' => null, 'price' => 14.00, 'category' => 'Postres'],
            ['name' => 'Copa Tentación', 'description' => null, 'price' => 14.00, 'category' => 'Postres'],
            ['name' => 'Copa Fondant', 'description' => null, 'price' => 14.00, 'category' => 'Postres'],
            ['name' => 'Mix frutado', 'description' => null, 'price' => 14.00, 'category' => 'Postres'],
            ['name' => 'Copa Beylis', 'description' => 'con licor Beylis', 'price' => 13.00, 'category' => 'Postres'],
            ['name' => 'Gusanito', 'description' => null, 'price' => 12.00, 'category' => 'Postres'],
            ['name' => 'Cubanaso', 'description' => 'con Ron', 'price' => 14.00, 'category' => 'Postres'],
            ['name' => 'Copa Tricolor', 'description' => null, 'price' => 10.00, 'category' => 'Postres'],
            ['name' => 'Coffee Helado', 'description' => 'con licor de cafe', 'price' => 10.00, 'category' => 'Postres'],
            ['name' => 'Muñeco de Nieve', 'description' => null, 'price' => 9.00, 'category' => 'Postres'],
            ['name' => 'Mazamorra de Calabaza', 'description' => null, 'price' => 5.00, 'category' => 'Postres'],
            ['name' => 'Barquito', 'description' => null, 'price' => 14.00, 'category' => 'Postres'],
            ['name' => 'Banana Royal', 'description' => null, 'price' => 9.00, 'category' => 'Postres'],
            ['name' => 'Copa Micky', 'description' => null, 'price' => 9.00, 'category' => 'Postres'],
            ['name' => 'Copa Buho', 'description' => null, 'price' => 10.00, 'category' => 'Postres'],
            ['name' => 'Copa Mosito', 'description' => null, 'price' => 9.00, 'category' => 'Postres'],
            ['name' => 'Frapuccino (Café)', 'description' => null, 'price' => 14.00, 'category' => 'Bebidas'],
            ['name' => 'Frappé de Cereza', 'description' => null, 'price' => 14.00, 'category' => 'Bebidas'],
            ['name' => 'Frappé de Oreo', 'description' => null, 'price' => 14.00, 'category' => 'Bebidas'],
            ['name' => 'Frappé de Chocolate', 'description' => null, 'price' => 14.00, 'category' => 'Bebidas'],
            ['name' => 'Milkshake de Durazno', 'description' => null, 'price' => 14.00, 'category' => 'Bebidas'],
            ['name' => 'Milkshake de Plátano', 'description' => null, 'price' => 14.00, 'category' => 'Bebidas'],
            ['name' => 'Inca Kola 3 Lt.', 'description' => null, 'price' => 16.00, 'category' => 'Bebidas'],
            ['name' => 'Inca Kola 2 Lt.', 'description' => null, 'price' => 12.00, 'category' => 'Bebidas'],
            ['name' => 'Inca Kola 1 1/2 Lt.', 'description' => null, 'price' => 11.00, 'category' => 'Bebidas'],
            ['name' => 'Inca Kola 1 Lt.', 'description' => null, 'price' => 8.00, 'category' => 'Bebidas'],
            ['name' => 'Gordita o Jumbo', 'description' => null, 'price' => 5.00, 'category' => 'Bebidas'],
            ['name' => 'Gaseosa Personal', 'description' => null, 'price' => 3.00, 'category' => 'Bebidas'],
            ['name' => 'Agua Mineral', 'description' => null, 'price' => 2.00, 'category' => 'Bebidas'],
            ['name' => 'Descartables 1/2 Lt.', 'description' => null, 'price' => 3.50, 'category' => 'Bebidas'],
            ['name' => 'Powerade', 'description' => null, 'price' => 2.50, 'category' => 'Bebidas'],
            ['name' => 'Cusqueña Negra', 'description' => null, 'price' => 12.00, 'category' => 'Cervezas'],
            ['name' => 'Cusqueña Trigo', 'description' => null, 'price' => 12.00, 'category' => 'Cervezas'],
            ['name' => 'Cerveza Pilsen', 'description' => null, 'price' => 10.00, 'category' => 'Cervezas'],
            ['name' => 'Cusqueña Cristal', 'description' => null, 'price' => 10.00, 'category' => 'Cervezas'],
            ['name' => 'Grolsch 450ml', 'description' => null, 'price' => 15.00, 'category' => 'Cervezas'],
            ['name' => 'Cervezas en lata', 'description' => 'Ch. Negra, Trigo, Pilsen, Dorada', 'price' => 6.00, 'category' => 'Cervezas'],
            ['name' => 'Chatas Importadas', 'description' => 'Peroni - Heineken - Stella Artois - Budwiser', 'price' => 6.00, 'category' => 'Cervezas'],
            ['name' => 'Calientito de Pisco', 'description' => null, 'price' => 18.00, 'category' => 'Calientitos'],
            ['name' => 'Calientito de Ron', 'description' => null, 'price' => 18.00, 'category' => 'Calientitos'],
            ['name' => 'Calientito de Menta', 'description' => null, 'price' => 18.00, 'category' => 'Calientitos'],
            ['name' => 'Calientito de Naranja', 'description' => null, 'price' => 18.00, 'category' => 'Calientitos'],
            ['name' => 'Calientitos Exóticos', 'description' => null, 'price' => 22.00, 'category' => 'Calientitos'],
            ['name' => 'Calientito de Jager', 'description' => null, 'price' => 22.00, 'category' => 'Calientitos'],
            ['name' => 'Maracumango 1 1/2 Lt.', 'description' => null, 'price' => 16.00, 'category' => 'Chichas y Refrescos'],
            ['name' => 'Maracumango 1 Lt.', 'description' => null, 'price' => 14.00, 'category' => 'Chichas y Refrescos'],
            ['name' => 'Maracufresa 1 1/2 Lt.', 'description' => null, 'price' => 16.00, 'category' => 'Chichas y Refrescos'],
            ['name' => 'Maracufresa 1 Lt.', 'description' => null, 'price' => 14.00, 'category' => 'Chichas y Refrescos'],
            ['name' => 'Limonada de Hierba Luisa 1 1/2 Lt.', 'description' => null, 'price' => 12.00, 'category' => 'Chichas y Refrescos'],
            ['name' => 'Limonada de Hierba Luisa 1 Lt.', 'description' => null, 'price' => 14.00, 'category' => 'Chichas y Refrescos'],
            ['name' => 'Naranjada 1 1/2 Lt.', 'description' => null, 'price' => 14.00, 'category' => 'Chichas y Refrescos'],
            ['name' => 'Naranjada 1 Lt.', 'description' => null, 'price' => 12.00, 'category' => 'Chichas y Refrescos'],
            ['name' => 'Limonada Frozen 1 1/2 Lt.', 'description' => null, 'price' => 14.00, 'category' => 'Chichas y Refrescos'],
            ['name' => 'Limonada Frozen 1 Lt.', 'description' => null, 'price' => 12.00, 'category' => 'Chichas y Refrescos'],
            ['name' => 'Vino Español Marquez de Riscal', 'description' => null, 'price' => 120.00, 'category' => 'Vinos'],
            ['name' => 'S. Queirolo o Tabernero 2 Lt', 'description' => null, 'price' => 55.00, 'category' => 'Vinos'],
            ['name' => 'Casillero del Diablo 750ml', 'description' => null, 'price' => 50.00, 'category' => 'Vinos'],
            ['name' => 'Vino Emotivo 750 ml.', 'description' => null, 'price' => 40.00, 'category' => 'Vinos'],
            ['name' => 'Vino Trapema 750 ml.', 'description' => null, 'price' => 35.00, 'category' => 'Vinos'],
            ['name' => 'Santiago Queirolo 750 ml.', 'description' => null, 'price' => 25.00, 'category' => 'Vinos'],
            ['name' => 'Vino Tabernero 750 ml.', 'description' => null, 'price' => 26.00, 'category' => 'Vinos'],
            ['name' => 'Kusi Wine frutado 750 ml', 'description' => null, 'price' => 25.00, 'category' => 'Vinos'],
            ['name' => 'Gran Feaduo 750ml', 'description' => null, 'price' => 40.00, 'category' => 'Vinos'],
            ['name' => 'Vino Tabernero selección Rose', 'description' => null, 'price' => 35.00, 'category' => 'Vinos'],
            ['name' => 'Vino S.Q Moscato 750 ml.', 'description' => null, 'price' => 25.00, 'category' => 'Vinos'],
            ['name' => 'Whisky - Vodka - Pisco - Ron - Gin - Tekila - Brandy', 'description' => 'Precio por shot o botella', 'price' => 0.00, 'category' => 'Licores'], // Precio no especificado, poner 0
            ['name' => 'Mate de Coca', 'description' => null, 'price' => 2.00, 'category' => 'Infusiones'],
            ['name' => 'Mate de Manzanilla', 'description' => null, 'price' => 1.50, 'category' => 'Infusiones'],
            ['name' => 'Mate de Anís', 'description' => null, 'price' => 1.50, 'category' => 'Infusiones'],
            ['name' => 'Café Pasado', 'description' => null, 'price' => 2.50, 'category' => 'Infusiones'],
            ['name' => 'Mate Digestivo', 'description' => null, 'price' => 1.50, 'category' => 'Infusiones'],
            ['name' => 'Infusiones Naturales', 'description' => null, 'price' => 1.50, 'category' => 'Infusiones'],
            ['name' => 'Piña Colada', 'description' => 'Ron blanco, Crema de coco, Jugo de piña, Leche', 'price' => 13.00, 'category' => 'Cócteles'],
            ['name' => 'Cielito Lindo', 'description' => 'Curacao azul, Crema de coco, Jugo de Naranja, Pisco', 'price' => 13.00, 'category' => 'Cócteles'],
            ['name' => 'Machu Picchu', 'description' => 'Pisco, Jarabe de granadina, Licor de menta, Jugo de naranja', 'price' => 13.00, 'category' => 'Cócteles'],
            ['name' => 'Mojito', 'description' => 'Ron blanco, Jugo de limón, Azúcar, Menta, Ginger ale', 'price' => 10.00, 'category' => 'Cócteles'],
            ['name' => 'Agua de Beber', 'description' => 'Ron, Curacao azul, Jarabe de granadina, Jugo de limón', 'price' => 12.00, 'category' => 'Cócteles'],
            ['name' => 'Ruso Negro', 'description' => 'Vodka, Kalhúa', 'price' => 9.00, 'category' => 'Cócteles'],
            ['name' => 'Calphiroska', 'description' => 'Vodka, Azúcar, Limón trozado', 'price' => 9.00, 'category' => 'Cócteles'],
            ['name' => 'Blue Margarita', 'description' => 'Tequila blanco, Curacao azul, Jugo de limón', 'price' => 11.00, 'category' => 'Cócteles'],
            ['name' => 'Amazonas', 'description' => 'Pisco, Anís, Jugo de naranja, granadina', 'price' => 10.00, 'category' => 'Cócteles'],
            ['name' => 'Italia 90', 'description' => 'Granadina, Anís, Licor de menta, Brandy', 'price' => 5.00, 'category' => 'Cócteles'],
            ['name' => 'Orgasmo', 'description' => 'Amaretto, Baileys irish crem', 'price' => 11.00, 'category' => 'Cócteles'],
            ['name' => 'Pantera Rosa', 'description' => 'Jarabe de Granadi, Crema de coco, Pisco, Leche', 'price' => 13.00, 'category' => 'Cócteles'],
            ['name' => 'Garibaldi', 'description' => 'Campari, Jugo de naranja, Ron', 'price' => 8.00, 'category' => 'Cócteles'],
            ['name' => 'Sex on the Beach', 'description' => 'Vodka, Jugo de piña, cranberry', 'price' => 10.00, 'category' => 'Cócteles'],
            ['name' => 'Oceanus', 'description' => 'Pisco, Licor de naranja, Crema de coco, Curacao azul, Nectar de piña', 'price' => 13.00, 'category' => 'Cócteles'],
            ['name' => 'Chilcano de Pisco', 'description' => 'Pisco, Jarabe de goma, Jugo de limón, Ginger ale', 'price' => 13.00, 'category' => 'Cócteles'],
            ['name' => 'Daiquiri de Durazno', 'description' => 'Ron Blanco, Durazno, Almíbar, Hielo', 'price' => 9.00, 'category' => 'Cócteles'],
            ['name' => 'Café Mexicano', 'description' => 'Café Caliente, Kahlúa, Tequila, Chantilly', 'price' => 9.00, 'category' => 'Cócteles'],
            ['name' => 'Khan Khan', 'description' => 'Ron, Granadina, Campari, Jugo de Piña, Jugo de Limón', 'price' => 13.00, 'category' => 'Cócteles'],
            ['name' => 'Piña Borracha', 'description' => 'Ron, Jarabe de goma, Nectar de piña, Jugo de limón', 'price' => 10.00, 'category' => 'Cócteles'],
            ['name' => 'Cuba Libre', 'description' => 'Ron Cubano, Coca cola, Limón, Hielo', 'price' => 10.00, 'category' => 'Cócteles'],
            ['name' => 'Mojito (Litro)', 'description' => null, 'price' => 30.00, 'category' => 'Refrescantes de Litro'],
            ['name' => 'Pisco Sour (Litro)', 'description' => null, 'price' => 30.00, 'category' => 'Refrescantes de Litro'],
            ['name' => 'Chilcano de Pisco (Litro)', 'description' => null, 'price' => 30.00, 'category' => 'Refrescantes de Litro'],
            ['name' => 'Cuba Libre (Litro)', 'description' => null, 'price' => 30.00, 'category' => 'Refrescantes de Litro'],
            ['name' => 'Corona Margarina', 'description' => 'Amarillo, Rojo, Verde, Azul', 'price' => 17.00, 'category' => 'Refrescantes de Litro'],
            ['name' => 'Maracuya Sour', 'description' => null, 'price' => 17.00, 'category' => 'Refrescantes de Litro'],

        ];

        foreach ($menuItems as &$item) {
            $item['created_at'] = now();
            $item['updated_at'] = now();
        }

        DB::table('menu_items')->insert($menuItems);
    }
}